### PR TITLE
Display mobile menu

### PR DESCRIPTION
**Pull request by eamador1**
Since the last review, the following changes were made:

- [ ] Display  mobile menu by clicking hamburger image
- [ ] Close mobile menu by clicking x image
- [ ] Move to appropriate page section when clicking menu option
- [ ] Close menu when menu option is clicked on

### CODE REVIEW

**Review by Zuhaib042 — COMMENTED** [review]
Hi @eamador1 @maximoortelli 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is a pair-programming activity. Although @maximoortelli  have made two commits in this project but his commits are mere spaces in the style.css file. kindly consider getting actual code commits from @maximoortelli  to fulfill the pair-programming requirement.
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by V-Blaze — CHANGES_REQUESTED** [review]
Hi @eamador1  , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

dcentl8-9b96e129-9725-401b-ac34-2feb990202a0

## Invalid Code Review Request

## You have submitted a project, that does not have all the required linters setup, Currently you do not have the Eslint JavaScript linters on your project. You need to add this as it's part of the requirement for this milestone. 
> For this project, you should add the [JavaScript + HTML + CSS linter](https://github.com/microverseinc/linters-config/tree/master/html-css-js).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by shella12 — APPROVED** [review]
Hi @eamador1 and @maximoortelli, 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights

- Menu closes on clicking (X) ✔️ 
- Menu opens on clicking hamburger  ✔️ 
- Menu links are working ✔️ 
- Implemented required design correctly 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by zieeco — COMMENTED** [review]
Hey  @eamador1 and @maximoortelli, 
According to this review [summary](https://github.com/eamador1/portfolio/pull/10#pullrequestreview-1437178178), Your project has been approved. Your dashboard action should change now!

**Pull request merged**
